### ISSUE TITLE
Allow specify other options like ignoreFiles, ignoreCatch or atLeast

### ISSUE THREAD

**Issue by timocov** [codechecks/type-coverage-watcher#4]
`type-coverage` package [supports](https://github.com/plantain-00/type-coverage/blob/master/packages/core/src/interfaces.ts#L22-L30) some options which might be useful (like ignoreFiles or ignoreCatch).

Also its CLI [has option `--at-least`](https://github.com/plantain-00/type-coverage#arguments) and I believe `type-coverage-watcher` might have that option also and fail if a coverage is down.

**Comment by krzkaczor** [comment]
@timocov yes this is definitely a good idea. Are you interested in making a PR @timocov, the codebase is really small right now.

**Comment by timocov** [comment]
Sure.
